import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Corporate Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <div className="p-12">
    <div className="">{children}</div>
  );
}
