import { DB } from "@/drizzle/setup";
import { Articles } from "@/drizzle/schema";
import { eq } from "drizzle-orm";
import { Breadcrumbs } from "@/components/breadcrumbs-builder";
import { Calendar, MapPin } from "lucide-react";
import Image from "next/image";

export default async function Article({ params }: { params: { article: string } }) {

  const [article]: any = await DB.select().from(Articles).where(eq(Articles.slug, params.article));

  return (
    <div>
      <Breadcrumbs current={article.category} path={[
        { label: "Home", href: "/" },
        { label: "Newsroom", href: "/newsroom" },
      ]} />

      <article className="grid lg:grid-cols-5 gap-12 py-12 px-8 lg:px-12">
        <section className="lg:col-span-3">
          <h1 className="font-bold text-3xl">{article.title}</h1>
          <span className="text-sm">{article.read_time} min read</span>
          <hr className="border-gray-800 dark:border-white my-4" />
          <div className="flex gap-4">
            <div className="flex gap-1">
              <Calendar className="mt-1" color="currentColor" size={16} />
              {new Date(article.posted_on).toDateString().slice(4)}
            </div>
            <div className="flex gap-1">
              <MapPin className="mt-1" color="currentColor" size={16} />
              {article.location}
            </div>
          </div>
          <hr className="border-gray-800 dark:border-white my-4" />
          <div className="text-justify">
            {JSON.parse(article.content).map((paragraph: string, index: number) => (
              <p
                key={index}
                className="mb-4"
              >{paragraph}</p>
            ))}
            <cite className="text-sm">This article was generated by Google Gemini, a generative AI model.</cite>
          </div>
        </section>
        <section className="lg:col-span-2">
          <Image
            src={article.image}
            alt="Test"
            width={1000}
            height={1000}
            className="rounded-xl shadow-xl"
            // layout="fill"
            // objectFit="cover"
          />
        </section>
      </article>

    </div>
  )
}
