name: Trigger Generative AI Action Endpoint

on:
  schedule:
    - cron: '10 1 * * 0'

jobs:
  send-trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Send POST request to generative endpoint
        run: |
          curl -X POST ${{ vars.API_ENDPOINT }} \
          -H "WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}"
